### ISSUE TITLE
Feature request + update

### ISSUE THREAD

**Issue by manashard** [CamperSamu/ItemCommander#14]
Any chance to update to 1.9.2?

Feature request:

Saving items in a file and giving them with /commander give "id" "playerName" "quantity"
Example file:
```
{
  "id": "test",
  "item": "minecraft:stone",
  "commands": /give @p minecraft:stone, /give @p minecraft:cobblestone, /give @p minecraft:diamond,
  "customName": {
    "text": "test",
    "color": "green"
  },
  "lore": [
    {
      "text": "line 1"
    },
    {
      "text": "line 2"
    }
  ]
}

```

**Comment by CamperSamu** [comment]
It was done as a private commission, forgot to update the mod with it.
Done in e6500b923cbe83e3421feff1172b41cab2345e48.
