### ISSUE TITLE
Commander Items on Lecterns

### ISSUE THREAD

**Issue by RotokEralil** [CamperSamu/ItemCommander#2]
This is exactly what I needed for my vanilla multiserver world.
I currently have the commands bound to books that port people to and from different servers "Myst" Ages style.
Is there a way to apply a command to a lectern with a book on it? 
Or have the object remain behind after use (I guess a drop command they teleport?)
I want to keep the book (or the lecturn with the book) where it is when they get teleported.

**Comment by CamperSamu** [comment]
For now no, but I'm adding this use to the to-do list!

**Comment by CamperSamu** [comment]
Added in 4d84651
