### ISSUE TITLE
[FAQ] Is ItemCommander incompatible with commands that require quotations?

### ISSUE THREAD

**Issue by Dimbywimby** [CamperSamu/ItemCommander#22]
Hiya! just letting you know; dialogue based commands don't seem to be working.

Eg;

[ /commander create "/tellraw @a ["Hello World"]" CONSUME SERVER 200 ] wont work thanks to the command itself featuring the quotation marks the plugin uses to define its commands.

Is there any work arounds i'm missing, or is this a bug?

Thank you!

**Comment by CamperSamu** [comment]
Heyo!
The mod works with those commands, BUT you either:

- Escape your qoutation marks with `\` like this: `\"`
  - `/commander create "/tellraw @a \"Hello World\"" CONSUME SERVER 200`

**OR**

- Use different quotations, like the apostrophe sign `'`
  - `/commander create '/tellraw @a "Hello World"' CONSUME SERVER 200`
  
  This should be added to the FAQs, but for now I'll just pin the issue.
  
  Thank you for your report!
