### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by Alkiasan** [CamperSamu/ItemCommander#6]
Forgive me if these are already possible, i'm not too advanced with commands..

I'd like to suggest a couple of features that'll help ItemCommander be a REALLY powerful mod to use!

1. Item cooldowns, for items that are running commands, it'd be nice if it was possible to set a cooldown for them so players can't spam them, just to give them some more customizability

2. Multiple commands ran by one item, I'm not sure if this is already possible, but it'd be super neat, to be able to add a command, then also add a particle command, so when the item is right-clicked it'll do a particle effect and run the command!

**Comment by CamperSamu** [comment]
For now I don't have time to work on Minecraft mods, so this summer I'll update everything to latest and add needed features.
Thanks to the good feedback!

**Comment by CamperSamu** [comment]
Ok so I finally got around to implement this changes with [21bbac7](https://github.com/CamperSamu/ItemCommander/commit/21bbac77be02af2f26fbf9ec89b0f337ed1f007c), going to update to 1.19 and migrate to Quilt soon!
